In [1]:
import os

import numpy as np
import pandas as pd
from scipy.io import wavfile
from scipy import signal

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset
from torchvision.transforms import Compose

# from sklearn.metrics import 

import tensorboardX
from tqdm import tqdm

import matplotlib.pyplot as plt

In [ ]:
    # test
    net.eval()
    with torch.no_grad():
        top5_accuracy = 0
        top1_accuracy = 0
        
        for iter_num, (label, spec) in tqdm(enumerate(testsetloader)):
            optimizer.zero_grad()
            label, spec = label.to(DEVICE), spec.to(DEVICE)
            probs = net(spec)
            
            # calculate Top-5 and Top-1 accuracy
            pred_top5 = probs.topk(5)[1].view(5)
            
            if label in pred_top5:
                # increment top-5 accuracy
                top5_accuracy += 1
                
                if label == pred_top5[0]:
                    # increment top-1 accuracy
                    top1_accuracy += 1
        
        top5_accuracy /= len(testsetloader)
        top1_accuracy /= len(testsetloader)
        
        TBoard.add_scalar('Metrics/test_top5', top5_accuracy, epoch_num)
        TBoard.add_scalar('Metrics/test_top1', top1_accuracy, epoch_num)

In [115]:
C = 7 # 1251
SIZE = (1, C)
probs = torch.rand(SIZE) # net(spec)
label = torch.randint(C, size=(1,)).type(torch.LongTensor)
pred_top5 = probs.topk(5)[1]
pred_top1 = probs.topk(1)[1]
print(probs)
print(label)
print(pred_top5)
print(label in pred_top5.view(5))
print(label in pred_top1.view(1))
print(label == pred_top5.view(5)[0])
if label == pred_top5.view(5)[0]:
    print('it works')

tensor([[0.4554, 0.7116, 0.3623, 0.6033, 0.4377, 0.2030, 0.6980]])
tensor([1])
tensor([[1, 6, 3, 0, 4]])
True
True
tensor([1], dtype=torch.uint8)
it works
