In [4]:
import os
import time

import numpy as np
import pandas as pd
from scipy.io import wavfile
from scipy import signal

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset
from torchvision.transforms import Compose

import tensorboardX
from tqdm import tqdm

import matplotlib.pyplot as plt

In [5]:
import warnings
warnings.filterwarnings('ignore') # scipy throws future warnings on fft (known bug)

In [6]:
def wav2spectrogram(path, segment_len=3, window='hamming', Tw=25, Ts=10, 
                    pre_emphasis=0.97, alpha=0.99, return_onesided=False):
    # read .wav file
    rate, samples = wavfile.read(path)
    
    ## parameters
    # frame duration (samples)
    Nw = int(rate * Tw * 1e-3)
    Ns = int(rate * (Tw - Ts) * 1e-3)
    # overlapped duration (samples)
    # 2 ** to the next pow of 2 of (Nw - 1)
    nfft = 2 ** (Nw - 1).bit_length()

    # preemphasis filter
    samples = np.append(samples[0], samples[1:] - pre_emphasis * samples[:-1])

    # removes DC component of the signal and add a small dither
    samples = signal.lfilter([1, -1], [1, -alpha], samples)
    dither = np.random.uniform(-1, 1, samples.shape)
    spow = np.std(samples)
    samples = samples + 1e-6 * spow * dither

    # segment selection
    upper_bound = len(samples) - segment_len * rate
    start = np.random.randint(0, upper_bound)
    end = start + segment_len * rate
    samples = samples[start:end]

    # spectogram
    _, _, spec = signal.spectrogram(samples, rate, window, Nw, Ns, nfft, 
                                    mode='magnitude', return_onesided=return_onesided)

    # just multiplying it by 1600 makes spectrograms in the paper and here "the same"
    spec *= rate / 10
    
    return spec

In [7]:
class IdentificationDatasetTrain(Dataset):
    
    def __init__(self, path, transform=None):
        self.path = path
        self.transform = transform
        
        iden_split_path = os.path.join(path, 'iden_split.txt')
        split = pd.read_table(iden_split_path, sep=' ', header=None, names=['phase', 'path'])
        split['label'] = split['path'].apply(lambda x: int(x.split('/')[0].replace('id1', '')) - 1)
        
        # make train/test id split (in paths class id numbering starts with 1)
        fullid_arr = np.arange(1251) # 1--1251
        testid_arr = np.arange(269, 309) # 270--309
        trainid_arr = np.setdiff1d(fullid_arr, testid_arr) # 1--1251 \ 270--309
        # subsetting ids for training
        mask = split['label'].isin(trainid_arr)
        self.dataset = split['path'][mask].reset_index(drop=True)
    
    def __len__(self):
        return len(self.dataset)
    
    def __getitem__(self, idx):
        # path
        track_path = self.dataset[idx]
        audio_path = os.path.join(self.path, 'audio', track_path)
        
        # extract label from path like id10003/L9_sh8msGV59/00001.txt
        # subtracting 1 because PyTorch assumes that C_i in [0, 1251-1]
        label = int(track_path.split('/')[0].replace('id1', '')) - 1
        # PyTorch complains if label > num_classes. For ex, num_classes=1211
        # label is 1250. train labels \in [0, ..., 268, 309, ..., 1250]. (269 + 942 = 1211)
        # therefore, we subtract 40 (# of test classes) from a label => label \in [0, 1211]
        if label >= 309:
            label -= 40
        
        # make a spectrogram from a .wavfile
        spec = wav2spectrogram(audio_path)
        
        if self.transform:
            spec = self.transform(spec)

        return label, spec

In [5]:
class Normalize(object):
    """Normalizes voice spectrogram (mean-varience)"""
    
    def __call__(self, spec):
        
        # (Freq, Time)
        # mean-variance normalization for every spectrogram (not batch-wise)
        mu = spec.mean(axis=1).reshape(512, 1)
        sigma = spec.std(axis=1).reshape(512, 1)
        spec = (spec - mu) / sigma

        return spec

class ToTensor(object):
    """Convert spectogram to Tensor."""
    
    def __call__(self, spec):
        F, T = spec.shape
        
        # now specs are of size (Freq, Time) and 2D but has to be 3D (channel dim)
        spec = spec.reshape(1, F, T)
        
        # make the ndarray to be of a proper type (was float64)
        spec = spec.astype(np.float32)
        
        return torch.from_numpy(spec)

In [6]:
class VoiceNet(nn.Module):

    def __init__(self, num_classes=2):
        super(VoiceNet, self).__init__()
        
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=96, kernel_size=7, stride=2, padding=1)
        self.conv2 = nn.Conv2d(in_channels=96, out_channels=256, kernel_size=5, stride=2, padding=1)
        self.conv3 = nn.Conv2d(in_channels=256, out_channels=256, kernel_size=3, padding=1)
        self.conv4 = nn.Conv2d(in_channels=256, out_channels=256, kernel_size=3, padding=1)
        self.conv5 = nn.Conv2d(in_channels=256, out_channels=256, kernel_size=3, padding=1)
        
        self.bn1 = nn.BatchNorm2d(num_features=96)
        self.bn2 = nn.BatchNorm2d(num_features=256)
        self.bn3 = nn.BatchNorm2d(num_features=256)
        self.bn4 = nn.BatchNorm2d(num_features=256)
        self.bn5 = nn.BatchNorm2d(num_features=256)
        self.bn6 = nn.BatchNorm2d(num_features=4096)
        self.bn7 = nn.BatchNorm1d(num_features=1024)
        
        self.relu = nn.ReLU()
        
        self.mpool1 = nn.MaxPool2d(kernel_size=3, stride=2)
        self.mpool2 = nn.MaxPool2d(kernel_size=3, stride=2)
        self.mpool5 = nn.MaxPool2d(kernel_size=(5, 3), stride=(3, 2))
        
        # Conv2d with weights of size (H, 1) is identical to FC with H weights
        self.fc6 = nn.Conv2d(in_channels=256, out_channels=4096, kernel_size=(9, 1))
        self.fc7 = nn.Linear(in_features=4096, out_features=1024)
        self.fc8 = nn.Linear(in_features=1024, out_features=num_classes)
        
    def forward_once(self, x):
        B, C, H, W = x.size()
        x = self.relu(self.bn1(self.conv1(x)))
        x = self.mpool1(x)
        x = self.relu(self.bn2(self.conv2(x)))
        x = self.mpool2(x)
        x = self.relu(self.bn3(self.conv3(x)))
        x = self.relu(self.bn4(self.conv4(x)))
        x = self.relu(self.bn5(self.conv5(x)))
        x = self.mpool5(x)
        x = self.relu(self.bn6(self.fc6(x)))
        
        _, _, _, W = x.size()
        self.apool6 = nn.AvgPool2d(kernel_size=(1, W))
        x = self.apool6(x)
        
        x = x.view(x.size(0), -1)
        
        if self.training:
            x = self.relu(self.bn7(self.fc7(x)))
            x = self.fc8(x)
        
        # we use the fc7 output for Hard Negative Mining (inference)
        else:
            x = self.fc7(x)
            x = F.normalize(x)
        
        # during training, there's no need for SoftMax because CELoss calculates it
        return x
    
    # phase: [training_iden, inference_negative_mining, training_siamese, verif_test]
    def forward(self, voice1, voice2=None, phase='train_iden'):
        if phase in ['train_iden', 'eval_mining']:
            return self.forward_once(voice1)
        
        elif phase in ['train_veri', 'eval_veri']:
            voice1 = self.forward_once(voice1)
            voice2 = self.forward_once(voice2)
            return voice1, voice2

In [7]:
DATASET_PATH = '/home/nvme/data/vc1/'
LOG_PATH = '/home/vladimir/nvme/logs/VoxCeleb/verif_class'
EPOCH_NUM = 30

# in shared code B = 100 but PyTorch throws CUDA out of memory at B = 97 
# though B=96 takes only 90.6% of the GPU Mem (bug?):
# https://discuss.pytorch.org/t/lesser-memory-consumption-with-a-larger-batch-in-multi-gpu-setup/29087
# B = 96
# but when 
torch.backends.cudnn.deterministic = True
# I can set B = 100
B = 100

WEIGHT_DECAY = 5e-4
LR_INIT = 1e-2
LR_LAST = 1e-4
# lr scheduler parameter
gamma = 10 ** (np.log10(LR_LAST / LR_INIT) / (EPOCH_NUM - 1))
MOMENTUM = 0.9
DEVICE = 'cuda:0'
NUM_WORKERS = 4
TBoard = tensorboardX.SummaryWriter(log_dir=LOG_PATH)

In [8]:
net = VoiceNet(num_classes=1211)
net.to(DEVICE)

transforms = Compose([
    Normalize(),
    ToTensor()
])

trainset = IdentificationDatasetTrain(DATASET_PATH, transform=transforms)
trainsetloader = torch.utils.data.DataLoader(trainset, batch_size=B, 
                                             num_workers=NUM_WORKERS, shuffle=True)

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), LR_INIT, MOMENTUM, weight_decay=WEIGHT_DECAY)
lr_scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=gamma)

RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:74

In [11]:
for epoch_num in range(EPOCH_NUM):
    lr_scheduler.step()
    
    # train
    net.train()
    
    for iter_num, (labels, specs) in tqdm(enumerate(trainsetloader)):
        optimizer.zero_grad()
        labels, specs = labels.to(DEVICE), specs.to(DEVICE)
        scores = net(specs)
        loss = criterion(scores, labels)
        loss.backward()
        optimizer.step()
        
        # TBoard
        step_num = epoch_num * len(trainsetloader) + iter_num
        TBoard.add_scalar('Metrics/train_loss', loss.item(), step_num)
        TBoard.add_scalar('Metrics/lr', lr_scheduler.get_lr()[0], step_num)
        
# when the training is finished save the model
torch.save(net.state_dict(), os.path.join(LOG_PATH, 'model_snapshot_{}.txt'.format(time.time())))
TBoard.close()

1487it [07:20,  4.08it/s]
1487it [07:25,  4.10it/s]
1487it [07:25,  4.09it/s]
1487it [07:25,  4.09it/s]
1487it [07:25,  4.09it/s]
1487it [07:25,  4.08it/s]
1487it [07:25,  4.08it/s]
1487it [07:25,  4.02it/s]
1487it [07:25,  4.10it/s]
1487it [07:25,  4.09it/s]
1487it [07:25,  4.03it/s]
1487it [07:25,  4.08it/s]
1487it [07:24,  4.09it/s]
1487it [07:25,  4.10it/s]
18it [00:06,  3.33it/s]Process Process-59:
Process Process-57:
Process Process-60:
Process Process-58:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vladimir/venv/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  F

KeyboardInterrupt: 

In [14]:
torch.save(net.state_dict(), os.path.join(LOG_PATH, 'model_snapshot_{}.txt'.format(time.time())))
TBoard.close()

In [18]:
pretrained_dict = torch.load(os.path.join(LOG_PATH, 'model_snapshot_1542979501.519298.txt'))

net = VoiceNet(num_classes=1211)
net.to(DEVICE)

model_dict = net.state_dict()

# 1. filter out unnecessary keys
pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict}
# 2. overwrite entries in the existing state dict
model_dict.update(pretrained_dict) 
# 3. load the new state dict
net.load_state_dict(model_dict)

FileNotFoundError: [Errno 2] No such file or directory: '/home/vladimir/nvme/logs/VoxCeleb/verif_class/model_snapshot_1542979501.519298.txt'

In [22]:
B = 10

net.train()
v1 = torch.rand((B, 1, 512, 298)).to(DEVICE)
print(net(v1, phase='train_iden').shape) # B, 1211

net.eval()
v1 = torch.rand((B, 1, 512, 298)).to(DEVICE)
v2 = torch.rand((B, 1, 512, 298)).to(DEVICE)
print(net(v1, phase='eval_mining').shape) # B, 1024
print(net(v2, phase='eval_mining').shape) # B, 1024

net.train()
for param in net.parameters():
    param.requires_grad = False
net.fc8 = nn.Linear(net.fc8.in_features, 1024).to(DEVICE)
v1 = torch.rand((B, 1, 512, 298)).to(DEVICE)
v2 = torch.rand((B, 1, 512, 298)).to(DEVICE)
print(net(v1, v2, phase='train_veri')[1].shape) # B, 1024

net.eval()
v1 = torch.rand((1, 1, 512, 2324)).to(DEVICE)
v2 = torch.rand((1, 1, 512, 3245)).to(DEVICE)
print(net(v1, v2, phase='eval_veri')[1].shape) # 1, 1024

torch.Size([10, 1211])
torch.Size([10, 1024])
torch.Size([10, 1024])
torch.Size([10, 1024])
torch.Size([1, 1024])


In [19]:
class VerificationDatasetTrain(Dataset):
    
    def __init__(self, path, model, batch_size, device, transform=None):
        self.path = path
        self.model = model
        self.transform = transform
        self.device = device
        
        fullid_arr = np.arange(1, 1252) # 1--1251
        testid_arr = np.arange(270, 310) # 270--309
        trainid_arr = np.setdiff1d(fullid_arr, testid_arr) # 1--1251 \ 270--309

        # split the set of ids into `len(trainid_arr) // batch_size` subsets
        self.splits = np.array_split(trainid_arr, len(trainid_arr) // batch_size)
        
    def __len__(self):
        return len(self.splits)
    
    def cosine_sim_matrix(tensor1, tensor2):
        B, D = tensor1.size()
        dot = tensor2 @ tensor1.t()
        norm1 = tensor1.norm(dim=1)
        norm2 = tensor2.norm(dim=1).view(1, B).t()
        dot /= norm1 * norm2
        return dot.t()
    
    def __getitem__(self, idx):
        
        ## POSITIVE PART
        ids = self.splits[idx]
        # shuffle ids to make sure that every negative pair will consist of voices of 
        # different identities at each iteration.
        ids = np.random.permutation(ids)
        anchors = [0] * len(ids)
        positives = [0] * len(ids)
        
        for i, id in enumerate(ids):
            # 265 -> id10265
            full_id = 'id1{:04d}'.format(id)
            # list all tracks for that id
            track_list = os.listdir(os.path.join(self.path, 'audio', full_id))
            # randomly select two tracks without replacement
            track1, track2 = np.random.choice(track_list, 2, replace=False)
            # select two voice segments
            voice1_path = os.path.join(self.path, 'audio', full_id, track1)
            voice2_path = os.path.join(self.path, 'audio', full_id, track2)
            # create spectrograms for selected .wav files
            spec1 = wav2spectrogram(voice1_path) 
            spec2 = wav2spectrogram(voice2_path)
            # add to the list
            anchors[i] = spec1
            positives[i] = spec2
            
        anchors = torch.cat(anchors).to(self.device)
        positives = torch.cat(positives).to(self.device)
        
        self.model.eval()
        anchors = self.model(anchors, 'eval_mining') # B, 1024
        positives = self.model(positives, 'eval_mining') # --//---
        
        # calculate a cosine similarity matrix
        sim_mat = cosine_sim_matrix(anchors, positives)
        
        
        # divide the current set of ids into two parts
        negatives_hnm, negatives_rand = np.array_split(ids, 2)
        
        ## HARD NEGATIVE MINING PART
        
        
        ## RANDOM PART
        

In [9]:
fullid_arr = np.arange(1, 1252) # 1--1251
testid_arr = np.arange(270, 310) # 270--309
trainid_arr = np.setdiff1d(fullid_arr, testid_arr) # 1--1251 \ 270--309

# split the set of ids into `len(trainid_arr) // batch_size` subsets
self_splits = np.array_split(trainid_arr, 1211 // 100)
ids = np.random.permutation(self_splits[0])
print(ids)
negatives_rand, negatives_hnm = np.array_split(ids, 2)
print(negatives_hnm)

[ 80  13  66  37   7  76  10  62  21  90  47  61  72  45  48  81  94  49
  67  71  44  33  26  55  42   2 101  38  60   5  93  27  36  20  59  24
  85  88  70  79  74  19   1  58  57  63  34  28  83  78  87  50   8  97
  51  17  52   4  56  99  18  84  89  54  75   6  14  43  68  77  31  82
  40  98  29  35  53  12  11  46  86  64  41  65  22  96  25  69   3  95
  73  91  39  15   9  16 100  30  23  92  32]
[ 50   8  97  51  17  52   4  56  99  18  84  89  54  75   6  14  43  68
  77  31  82  40  98  29  35  53  12  11  46  86  64  41  65  22  96  25
  69   3  95  73  91  39  15   9  16 100  30  23  92  32]


In [210]:
def cosine_similarity_matrix_loop(tensor1, tensor2):
    sim = [[F.cosine_similarity(a, b, dim=0) for a in tensor2] for b in tensor1]
    return torch.Tensor(sim)

def cosine_similarity_matrix_vectorized(tensor1, tensor2):
    B, D = tensor1.size()
    dot = tensor2 @ tensor1.t()
    norm1 = tensor1.norm(dim=1)
    norm2 = tensor2.norm(dim=1).view(1, B).t()
    dot /= norm1 * norm2
    return dot.t()

B = 5

anchors = torch.randn(B, 4)
positives = torch.randn(B, 4)

print(anchors)
print()
print(positives)
print(anchors.size(), positives.size())

print(F.cosine_similarity(anchors, positives))

sim = [[F.cosine_similarity(a, b, dim=0) for a in positives] for b in anchors]
sim = torch.Tensor(sim)
print(sim)
print(cosine_similarity_matrix_loop(anchors, positives))
print(cosine_similarity_matrix_vectorized(anchors, positives))
print((cosine_similarity_matrix_loop(anchors, positives) - cosine_similarity_matrix_vectorized(anchors, positives)).sum())

tensor([[-0.2210, -1.5022,  1.0385, -0.0150],
        [ 1.9777, -0.3181,  0.0651, -1.0455],
        [ 1.2548, -0.4052, -0.2234,  0.0043],
        [ 1.6252,  0.2383,  0.6327,  0.9166],
        [-0.3791, -0.5218, -0.2294, -1.8437]])

tensor([[-1.2607,  3.0024,  1.4890, -0.3889],
        [ 0.5755, -3.1204,  0.0870, -0.7363],
        [-0.6371,  0.5573, -1.1816, -1.9365],
        [-0.2033, -1.8213, -0.6009, -1.3229],
        [ 0.3952, -1.6698,  0.2164,  0.5675]])
torch.Size([5, 4]) torch.Size([5, 4])
tensor([-0.4044,  0.3945, -0.2377, -0.5079, -0.1046])
tensor([[-0.4044,  0.7777, -0.4253,  0.5060,  0.7876],
        [-0.3617,  0.3945,  0.0933,  0.2877,  0.1782],
        [-0.6504,  0.4507, -0.2377,  0.1955,  0.4628],
        [-0.1046, -0.0662, -0.7128, -0.5079,  0.2495],
        [-0.1007,  0.4288,  0.7963,  0.7836, -0.1046]])
tensor([[-0.4044,  0.7777, -0.4253,  0.5060,  0.7876],
        [-0.3617,  0.3945,  0.0933,  0.2877,  0.1782],
        [-0.6504,  0.4507, -0.2377,  0.1955,  0.4628],
    

In [266]:
print(sim)
sim_sorted, sim_sorted_idx = sim.sort(dim=1)
print(sim_sorted)
print(sim_sorted_idx)
# Given a sim matrix Dij, if i=j a value corresponds to a similarity between 
# positive pairs -> we need to prevent them from getting to the negative samples
# First, we need to remove i=j elements.
mask = (sim_sorted_idx != torch.arange(B).repeat(1, B).view(B, B).t())
sim_sorted_idx_rm = sim_sorted_idx[mask].view(B, B-1)
print(sim_sorted_idx_rm)
# select the indices for appropriately hard samples
tau = 0.1
idx_threshold = round(tau * (B-2))
# only half of the batch size -> B // 2
hnm_idxs = sim_sorted_idx_rm[B // 2:, idx_threshold]
print(hnm_idxs)
idx_threshold_rand = torch.from_numpy(np.random.uniform(size=(B, 1)) * (B-1)).long()
# print(idx_threshold_rand)
# rand_idxs = sim_sorted_idx_rm[:B // 2, idx_threshold_rand]
rand_idxs = torch.gather(sim_sorted_idx_rm, dim=1, index=idx_threshold_rand)[:B // 2]
print(rand_idxs)
print(hnm_idxs.shape, rand_idxs.shape)
print(torch.cat([rand_idxs.view(-1), hnm_idxs.view(-1)]))
negatives = positives[torch.cat([rand_idxs.view(-1), hnm_idxs.view(-1)]), :]
print(negatives)

tensor([[-0.4044,  0.7777, -0.4253,  0.5060,  0.7876],
        [-0.3617,  0.3945,  0.0933,  0.2877,  0.1782],
        [-0.6504,  0.4507, -0.2377,  0.1955,  0.4628],
        [-0.1046, -0.0662, -0.7128, -0.5079,  0.2495],
        [-0.1007,  0.4288,  0.7963,  0.7836, -0.1046]])
tensor([[-0.4253, -0.4044,  0.5060,  0.7777,  0.7876],
        [-0.3617,  0.0933,  0.1782,  0.2877,  0.3945],
        [-0.6504, -0.2377,  0.1955,  0.4507,  0.4628],
        [-0.7128, -0.5079, -0.1046, -0.0662,  0.2495],
        [-0.1046, -0.1007,  0.4288,  0.7836,  0.7963]])
tensor([[2, 0, 3, 1, 4],
        [0, 2, 4, 3, 1],
        [0, 2, 3, 1, 4],
        [2, 3, 0, 1, 4],
        [4, 0, 1, 3, 2]])
tensor([[2, 3, 1, 4],
        [0, 2, 4, 3],
        [0, 3, 1, 4],
        [2, 0, 1, 4],
        [0, 1, 3, 2]])
tensor([0, 2, 0])
tensor([[2],
        [2]])
torch.Size([3]) torch.Size([2, 1])
tensor([2, 2, 0, 2, 0])
tensor([[-0.6371,  0.5573, -1.1816, -1.9365],
        [-0.6371,  0.5573, -1.1816, -1.9365],
        [-1.260

In [27]:
input1 = torch.randn(5, 128)
input2 = torch.randn(5, 128)
# output = cosine_similarity_matrix_loop(input1, input2)
output = [[F.cosine_similarity(a, b, dim=0) for a in input1] for b in input2]
torch.cat(output[0])
output

RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

In [14]:
B = 5
anchors = torch.randint(high=10, size=(B, 1024))
positives = torch.randint(high=10, size=(B, 1024))

In [16]:
print(anchors)
print()
print(positives)
dists = (anchors**2).sum(dim=1).view(-1, 1) + (positives**2).sum(dim=1) - 2*anchors.matmul(positives.t())
dists = np.sqrt(dists)
print(dists)
dists_sorted, dists_sorted_idx = dists.sort(dim=1)
print(dists_sorted, dists_sorted_idx)
tau = 0.02
idx_threshold = round(tau * (B-1))
# Given a distance matrix Dij, if i=j a value corresponds to a distance between 
# positive pairs -> we need to prevent them from getting to the negative samples
# First, we need to remove i=j elements.
mask = (dists_sorted_idx != torch.arange(B).repeat(1, B).view(B, B).t())
dists_sorted_idx_rm = dists_sorted_idx[mask].view(B, B-1)
print(dists_sorted_idx_rm)
selected_idx = dists_sorted_idx_rm[:, idx_threshold]
print(selected_idx)


tensor([[0., 3., 8.,  ..., 0., 8., 5.],
        [1., 3., 6.,  ..., 4., 6., 8.],
        [8., 2., 2.,  ..., 2., 0., 6.],
        [3., 7., 4.,  ..., 5., 0., 8.],
        [3., 4., 0.,  ..., 8., 8., 8.]])

tensor([[1., 7., 7.,  ..., 1., 5., 8.],
        [5., 5., 6.,  ..., 9., 2., 8.],
        [2., 1., 7.,  ..., 7., 2., 5.],
        [8., 8., 7.,  ..., 2., 0., 5.],
        [4., 7., 3.,  ..., 4., 3., 1.]])
tensor([[127.5853, 128.9341, 133.3079, 127.9922, 128.5924],
        [129.3406, 128.7983, 129.4836, 123.9637, 128.4640],
        [130.8587, 130.1768, 132.6311, 130.7134, 132.0984],
        [131.9886, 131.0000, 132.9962, 126.4002, 131.0000],
        [132.4009, 130.7746, 131.8294, 129.6302, 130.0615]])
tensor([[127.5853, 127.9922, 128.5924, 128.9341, 133.3079],
        [123.9637, 128.4640, 128.7983, 129.3406, 129.4836],
        [130.1768, 130.7134, 130.8587, 132.0984, 132.6311],
        [126.4002, 131.0000, 131.0000, 131.9886, 132.9962],
        [129.6302, 130.0615, 130.7746, 131.8294, 132.400

In [17]:
print(anchors)
a = anchors[:3]
print(a)
a[0] = 23
print(a)
print(anchors)

tensor([[0., 3., 8.,  ..., 0., 8., 5.],
        [1., 3., 6.,  ..., 4., 6., 8.],
        [8., 2., 2.,  ..., 2., 0., 6.],
        [3., 7., 4.,  ..., 5., 0., 8.],
        [3., 4., 0.,  ..., 8., 8., 8.]])
tensor([[0., 3., 8.,  ..., 0., 8., 5.],
        [1., 3., 6.,  ..., 4., 6., 8.],
        [8., 2., 2.,  ..., 2., 0., 6.]])
tensor([[23., 23., 23.,  ..., 23., 23., 23.],
        [ 1.,  3.,  6.,  ...,  4.,  6.,  8.],
        [ 8.,  2.,  2.,  ...,  2.,  0.,  6.]])
tensor([[23., 23., 23.,  ..., 23., 23., 23.],
        [ 1.,  3.,  6.,  ...,  4.,  6.,  8.],
        [ 8.,  2.,  2.,  ...,  2.,  0.,  6.],
        [ 3.,  7.,  4.,  ...,  5.,  0.,  8.],
        [ 3.,  4.,  0.,  ...,  8.,  8.,  8.]])
